version: '3'

services:
  node:
    build: 
      context: ./backend/node
      dockerfile: Dockerfile
    container_name: node
    ports:
      - 8080:8080
    depends_on:
      - vision-db
    # tty: true
    # networks:
    #   - dbNetWork
    volumes:
      - ./backend/node/src:/app/src

  react:
    build: 
      context: ./frontend/react-app
      dockerfile: Dockerfile
    container_name: react
    ports:
      - 3000:3000
    depends_on:
      - node
    # networks:
    #   - dbNetWork
    volumes:
      - ./frontend/react-app/public:/app/public
      - ./frontend/react-app/src:/app/src
      - ./frontend/react-app/package.json:/app/package.json
      - ./frontend/react-app/package-lock.json:/app/package-lock.json
# networks:
#   dbNetWork:

    
