version: '3'

services:
  vision-db:
    container_name: vision-db
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    volumes:
      - ./config/vision-398320-fe9ad4140da9.json:/config/vision-398320-fe9ad4140da9.json
    ports:
      - "3306:3306"
    # environment:
    #   - MYSQL_ROOT_HOST=%
    #   - MYSQL_DATABASE=${DB_NAME}
    #   - MYSQL_USER=${DB_USER}
    #   - MYSQL_PASSWORD=${DB_PASS}
    #   - MYSQL_ROOT_PASSWORD=${DB_PASS}
    #   - TZ=${TZ}
    restart: always
    command:
      ["/cloud_sql_proxy",
      "-instances=vision-398320:asia-northeast1:vision-db=tcp:127.0.0.1:3306",
      "-credential_file=/config/vision-398320-fe9ad4140da9.json"]
  node:
    build: 
      context: ./backend/node
      dockerfile: Dockerfile
    container_name: node
    ports:
      - 8080:8080
    depends_on:
      - vision-db
    # tty: true
    # networks:
    #   - dbNetWork
    volumes:
      - ./backend/node/src:/app/src

  react:
    build: 
      context: ./frontend/react-app
      dockerfile: Dockerfile
    container_name: react
    ports:
      - 3000:3000
    depends_on:
      - node
    # networks:
    #   - dbNetWork
    volumes:
      - ./frontend/react-app/public:/app/public
      - ./frontend/react-app/src:/app/src
      - ./frontend/react-app/package.json:/app/package.json
      - ./frontend/react-app/package-lock.json:/app/package-lock.json
# networks:
#   dbNetWork:

    
